---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install apache2
  apt:
    name: apache2
    state: present

- name: start apache2 service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Deploy costume index..html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"
